project: research_task_hws
name: HNet_experiment
dataset: resisc45

epochs: 120
batch_size: 32
lr: 0.0005968
weight_decay: 0.0047469
patience: 8

channels_per_block: [32, 64, 128]
layers_per_block: 3
gated: true
kernel_size: 3
pool_stride: 2
pool_sigma: 1.2
invariant_channels: 128
use_bn: true
non_linearity: none
max_rot_order: 2

img_size: 128
n_classes: 45
gray_scale: false
