project: research_task_hws
name: colorectal_hist_experiment
dataset: colorectal_hist

epochs: 160
batch_size: 32
lr: 0.00037199
weight_decay: 0.0000028131
patience: 8

channels_per_block: [64, 64, 64]
layers_per_block: 2
gated: true
kernel_size: 3
pool_stride: 2
pool_sigma: 0.9
invariant_channels: 128
use_bn: true
non_linearity: none
max_rot_order: 1

img_size: 125
n_classes: 8
gray_scale: false