name: equi-act
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.7.0=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h5eee18b_1
  - asttokens=3.0.0=py310h06a4308_0
  - async-lru=2.0.4=py310h06a4308_0
  - babel=2.16.0=py310h06a4308_0
  - beautifulsoup4=4.12.3=py310h06a4308_0
  - bleach=6.2.0=py310h06a4308_0
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - cffi=1.17.1=py310h1fdaa30_1
  - comm=0.2.1=py310h06a4308_0
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - h11=0.16.0=py310h06a4308_0
  - httpcore=1.0.9=py310h06a4308_0
  - httpx=0.28.1=py310h06a4308_0
  - ipykernel=6.29.5=py310h06a4308_1
  - ipython=8.30.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - json5=0.9.25=py310h06a4308_0
  - jsonschema=4.23.0=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - jupyter-lsp=2.2.5=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_core=5.7.2=py310h06a4308_0
  - jupyter_events=0.12.0=py310h06a4308_0
  - jupyter_server=2.15.0=py310h06a4308_0
  - jupyter_server_terminals=0.5.3=py310h06a4308_0
  - jupyterlab=4.3.4=py310h06a4308_0
  - jupyterlab_pygments=0.3.0=py310h06a4308_0
  - jupyterlab_server=2.27.3=py310h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mistune=3.1.2=py310h06a4308_0
  - nbclient=0.10.2=py310h06a4308_0
  - nbconvert-core=7.16.6=py310h06a4308_0
  - nbformat=5.10.4=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - notebook=7.3.2=py310h06a4308_1
  - notebook-shim=0.2.4=py310h06a4308_0
  - openssl=3.0.16=h5eee18b_0
  - overrides=7.4.0=py310h06a4308_0
  - packaging=24.2=py310h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py310h06a4308_0
  - pexpect=4.9.0=py310h06a4308_0
  - pip=25.0=py310h06a4308_0
  - prometheus_client=0.21.1=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.20.0=py310h06a4308_0
  - python-json-logger=3.2.1=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py310h06a4308_0
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.22.3=py310h4aa5aa6_0
  - send2trash=1.8.2=py310h06a4308_1
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py310h06a4308_0
  - tinycss2=1.4.0=py310h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - wcwidth=0.2.13=py310h06a4308_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autograd==1.7.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.0.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - escnn==1.0.11
      - filelock==3.18.0
      - fonttools==4.58.4
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hf-xet==1.1.8
      - huggingface-hub==0.34.4
      - idna==3.10
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - lie-learn==0.0.2
      - lightning==2.5.0.post0
      - lightning-utilities==0.14.0
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - pandas==2.3.2
      - pillow==11.1.0
      - platformdirs==4.3.6
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - py3nj==0.2.1
      - pyarrow==21.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pymanopt==2.2.1
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.2
      - requests==2.32.3
      - scipy==1.15.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - smmap==5.0.2
      - sympy==1.13.1
      - torch==2.6.0
      - torch-geometric==2.6.1
      - torchmetrics==1.6.3
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - wandb==0.19.8
      - xxhash==3.5.0
      - yarl==1.18.3
prefix: /home/petr/anaconda3/envs/equi-act
